### ISSUE TITLE
Random crash due to logfile.txt is in use

### ISSUE THREAD

**Issue by Leayal** [Arks-Layer/PSO2TweakerV4#2]
Sometimes it show in richtextbox, sometimes it cause the app crash. This also happened at startup too, which make Tweaker looks like `can't start`, but it actually is `started but crashed before showing up`.

> IOException: The process cannot access the file '...\logfile.txt' because it is being used by another process

That is what the exeception said, what i'm wondering is `The file is being accessed in two (or more) threads at the same time?`

Please check out the issue. (I think you can make use the [ConcurrentStack](https://msdn.microsoft.com/en-us/library/dd267331(v=vs.110).aspx) class to make a thread-safe log file.)

**Comment by Aida-Enna** [comment]
This typically happens when another instance of Tweaker is still open and it is still locking the logfile. You've had it throw this error with only one Tweaker process? If so, can you find a way to reproduce it?

**Comment by Leayal** [comment]
I didn't leave another instance running nor anything access that logfile.txt

To reprodce: I just restart the tweaker over and over and sometimes it occurred.

If possible, I think it's because of [this line at the file Program.vb](https://github.com/Arks-Layer/PSO2TweakerV4/blob/7716a9d81157943fcb18d689001b79178cc6857f/PSO2TweakerVer2/My/Program.vb#L290)

Like...In a very rare case, the [Helper.Log() at line 366](https://github.com/Arks-Layer/PSO2TweakerV4/blob/7716a9d81157943fcb18d689001b79178cc6857f/PSO2TweakerVer2/My/Program.vb#L366) is being called right when the log file is being accessed at these line [291~308](https://github.com/Arks-Layer/PSO2TweakerV4/blob/7716a9d81157943fcb18d689001b79178cc6857f/PSO2TweakerVer2/My/Program.vb#L291) (or in later lines)

**Comment by Leayal** [comment]
Close the issue because it has been passed 10 days since last post.
Feel free to open the issue again if you want.
